version: '3.8'

services:
  postgres-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=ecommerce_admin
      - POSTGRES_PASSWORD=ecommerce_pw

  django-backend:
    build: ./ecommerce_web_proj
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ecommerce_web_proj/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres-db

  vue-frontend:
    build: ./ecommerce_web_vue
    volumes:
      - ./ecommerce_web_vue/:/usr/src/frontend/
      - /usr/src/frontend/node_modules
    ports:
      - 8080:8080

volumes:
  postgres_data: